#!/usr/bin/env python3
"""Manifest → agent-file generator (task B3.1; contract: control/manifests/README.md).

Input:  control/manifests/*.yaml validating against control/schemas/manifest.json.
Output: control/manifests/_generated/<agent_id>/{IDENTITY.md,SOUL.md,AGENTS.md,TOOLS.md}

Guarantees:
  * Deterministic — same input produces byte-identical output (CI-verifiable
    via --check).
  * Generation NEVER registers or activates an agent in OpenClaw (BA-2.4):
    this script only writes Markdown files into _generated/.
  * Deny-by-default tool rendering; a tool listed in both allowed and denied
    is rendered denied ("deny wins") and flagged.

Usage:
  manifest_generator.py            # (re)generate all
  manifest_generator.py --check    # exit 1 if _generated/ is stale or wrong
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

import yaml
from jsonschema import Draft7Validator

REPO_ROOT = Path(__file__).resolve().parents[2]
MANIFEST_DIR = REPO_ROOT / "control" / "manifests"
GENERATED_DIR = MANIFEST_DIR / "_generated"
SCHEMA_PATH = REPO_ROOT / "control" / "schemas" / "manifest.json"
DIGEST_PATH = REPO_ROOT / "company" / "digest-v1.1.md"
POLICIES_PATH = REPO_ROOT / "control" / "models" / "policies.yaml"

HEADER = "<!-- GENERATED by control/scripts/manifest_generator.py — do not hand-edit -->\n"

# v1 §10 — embedded VERBATIM (source of truth: the v1 document).
UNIVERSAL_WORKING_METHOD = """\
## Universal Working Method (v1 §10)

1. **Receive:** identify task, requester, intended outcome, priority, risk, and dependencies.
2. **Clarify:** identify missing, conflicting, or ambiguous information.
3. **Classify:** determine impact, complexity, data sensitivity, and risk.
4. **Plan:** define steps, artifacts, reviewers, evidence, and completion criteria.
5. **Execute:** perform role-specific work using approved inputs.
6. **Verify:** self-check against requirements, standards, and failure modes.
7. **Document:** record decisions, assumptions, evidence, limitations, and open issues.
8. **Handoff:** submit a complete artifact package to the next owner.
9. **Respond to review:** correct rejected work without hiding findings.
10. **Improve:** record reusable lessons and preventive improvements.
"""

# v1 §11 — embedded VERBATIM.
UNIVERSAL_THINKING_FRAMEWORK = """\
## Universal Thinking Framework (v1 §11)

```text
Observe
  → Understand business and user context
  → Identify objectives and measurable outcomes
  → Identify constraints, assumptions, dependencies, and risks
  → Gather evidence and current industry practices
  → Generate credible alternatives
  → Compare trade-offs
  → Select and justify the best option
  → Verify against company rules and role standards
  → Produce complete artifacts
  → Perform an independent-minded self-review
  → Submit with explicit status, evidence, and unresolved items
```
"""


class ManifestError(Exception):
    """Validation failure; message lists every problem."""


def load_manifests() -> list[tuple[Path, dict]]:
    validator = Draft7Validator(json.loads(SCHEMA_PATH.read_text()))
    known_policies = set(
        (yaml.safe_load(POLICIES_PATH.read_text()) or {}).get("policies", {})
    )
    problems: list[str] = []
    manifests: list[tuple[Path, dict]] = []
    seen_ids: dict[str, str] = {}

    paths = sorted(
        p for p in MANIFEST_DIR.glob("*.yaml") if p.parent == MANIFEST_DIR
    )
    if not paths:
        raise ManifestError("no manifests found in control/manifests/")

    for path in paths:
        rel = path.relative_to(REPO_ROOT)
        try:
            data = yaml.safe_load(path.read_text())
        except yaml.YAMLError as exc:
            problems.append(f"{rel}: not valid YAML ({exc})")
            continue
        if not isinstance(data, dict):
            problems.append(f"{rel}: manifest must be a YAML mapping")
            continue
        for err in sorted(validator.iter_errors(data), key=str):
            where = "/".join(str(p) for p in err.absolute_path) or "(root)"
            problems.append(f"{rel}: {where}: {err.message}")
        agent_id = data.get("agent_id")
        if isinstance(agent_id, str):
            expected = f"{agent_id.lower()}.yaml"
            if path.name != expected:
                problems.append(f"{rel}: filename must be {expected}")
            if agent_id in seen_ids:
                problems.append(
                    f"{rel}: duplicate agent_id {agent_id} (also in {seen_ids[agent_id]})"
                )
            seen_ids[agent_id] = str(rel)
        policy = data.get("model_policy")
        if known_policies and policy not in known_policies:
            problems.append(
                f"{rel}: model_policy {policy!r} not in control/models/policies.yaml "
                f"policies {sorted(known_policies)}"
            )
        manifests.append((path, data))

    if problems:
        raise ManifestError("\n".join(problems))
    return manifests


def digest_block(role_id: str, role_name: str) -> str:
    """The digest file VERBATIM, with only the role placeholders substituted."""
    text = DIGEST_PATH.read_text(encoding="utf-8")
    return text.replace("{ROLE_ID}", role_id).replace("{ROLE_NAME}", role_name)


def bullets(items: list[str]) -> str:
    return "\n".join(f"- {item}" for item in items)


def render_identity(m: dict) -> str:
    return (
        f"{HEADER}# IDENTITY.md — {m['agent_id']}\n\n"
        f"- **Name:** {m['agent_id']} — {m['name']}\n"
        f"- **Agent version:** {m['agent_version']}\n"
        f"- **Role contract:** {m['role_contract_version']}\n"
        f"- **Status:** {m['status']} (activation is a human act, never a generator act)\n\n"
        f"## Identity\n\n{m['role_contract']['identity'].rstrip()}\n"
    )


def render_soul(m: dict) -> str:
    rc = m["role_contract"]
    return (
        f"{HEADER}# SOUL.md — {m['agent_id']} ({m['name']})\n\n"
        f"## Mission\n\n{rc['mission'].rstrip()}\n\n"
        f"{UNIVERSAL_THINKING_FRAMEWORK}\n"
        f"## Role principles\n\n{bullets(rc['principles'])}\n"
    )


def render_agents(m: dict) -> str:
    rc = m["role_contract"]
    return (
        f"{HEADER}"
        f"{digest_block(m['agent_id'], m['name'])}\n"
        f"{UNIVERSAL_WORKING_METHOD}\n"
        f"## Responsibilities\n\n{bullets(rc['responsibilities'])}\n\n"
        f"## Collaboration\n\n{bullets(rc['collaboration'])}\n\n"
        f"## Escalation\n\n{bullets(rc['escalation'])}\n"
    )


def render_tools(m: dict) -> str:
    allowed = list(m["allowed_tools"])
    denied = list(m["denied_tools"])
    overlap = sorted(set(allowed) & set(denied))
    effective_allowed = [t for t in allowed if t not in overlap]
    lines = [
        HEADER,
        f"# TOOLS.md — {m['agent_id']} (deny-by-default)\n",
        "Any tool NOT listed under Allowed is DENIED. A tool listed under both",
        "Allowed and Denied is DENIED (deny wins).\n",
        "## Allowed\n",
        bullets(effective_allowed) or "- (none)",
        "\n## Denied\n",
        bullets(sorted(set(denied) | set(overlap))) or "- (none)",
    ]
    if overlap:
        lines.append(
            "\n## Conflicts resolved (deny wins)\n\n" + bullets(overlap)
        )
    lines.append(
        f"\n## Policy references\n\n- model_policy: {m['model_policy']}\n"
        f"- memory_policy: {m['memory_policy']}\n"
        f"- risk_ceiling: {m['risk_ceiling']}\n"
        f"- required_evals: {', '.join(m['required_evals'])}\n"
    )
    return "\n".join(lines)


def generate(manifests: list[tuple[Path, dict]]) -> dict[str, str]:
    """Return {relative_output_path: content} for all agents, deterministically."""
    out: dict[str, str] = {}
    for _, m in sorted(manifests, key=lambda t: t[1]["agent_id"]):
        base = f"{m['agent_id']}"
        out[f"{base}/IDENTITY.md"] = render_identity(m)
        out[f"{base}/SOUL.md"] = render_soul(m)
        out[f"{base}/AGENTS.md"] = render_agents(m)
        out[f"{base}/TOOLS.md"] = render_tools(m)
    return out


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true",
                        help="verify _generated/ is exactly regenerable; write nothing")
    args = parser.parse_args(argv)

    try:
        manifests = load_manifests()
    except ManifestError as exc:
        print(f"manifest-generator: FAIL\n{exc}")
        return 1

    rendered = generate(manifests)

    if args.check:
        problems = []
        for rel, content in rendered.items():
            path = GENERATED_DIR / rel
            if not path.exists():
                problems.append(f"missing: _generated/{rel}")
            elif path.read_text(encoding="utf-8") != content:
                problems.append(f"stale: _generated/{rel}")
        expected = set(rendered)
        actual = {
            str(p.relative_to(GENERATED_DIR))
            for p in GENERATED_DIR.rglob("*.md")
        } if GENERATED_DIR.exists() else set()
        for orphan in sorted(actual - expected):
            problems.append(f"orphan: _generated/{orphan}")
        for line in problems:
            print(f"FAIL {line}")
        if problems:
            print(f"manifest-generator --check: {len(problems)} problem(s)")
            return 1
        print(f"manifest-generator --check: clean ({len(manifests)} agent(s))")
        return 0

    for rel, content in rendered.items():
        path = GENERATED_DIR / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    print(f"manifest-generator: wrote {len(rendered)} files for {len(manifests)} agent(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
